service: &service
  name: hangman

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  environment:
    USRV_STAGE: ${self:provider.stage}
custom:
  service: *service
  webpack:
    packager: "npm"
    includeModules:
      forceInclude:
        - jsonpath
      forceExclude:
        - aws-sdk
plugins:
  - serverless-webpack
package:
  individually: true
  excludeDevDependencies: true
  exclude:
    - "src/handler/*.LICENSE"

functions:
  hello:
    handler: src/handler/HelloHandler.main
  connectSession:
    handler: src/handler/ConnectSessionHandler.main
  connect:
    handler: src/handler/ConnectHandler.main
  disconnect:
    handler: src/handler/DisconnectHandler.main